### ISSUE TITLE
Task title view is too big

### ISSUE THREAD

**Issue by pulkomandy** [AdrianArroyoCalle/haiku-todo#11]
The task title is shown with a rather huge font, making the list views too small to see the full task title there, if you have long task names.

**Comment by AdrianArroyoCalle** [comment]
![30px to 20px](http://i.imgur.com/ZURRPSv.png)

I've changed the size from 30px to 20px. Is it still big or is it correct?

**Comment by pulkomandy** [comment]
I would use a multiple of the current font size, maybe current font size * 1.5. This way it will work nicely also for people with high-DPI displays.

**Comment by AdrianArroyoCalle** [comment]
Ok
