### ISSUE TITLE
Auth token for Google Tasks is not stored

### ISSUE THREAD

**Issue by pulkomandy** [AdrianArroyoCalle/haiku-todo#14]
I need to login each time I start haikutodo. There should be a way to make the authentication permanent or at least longer than the app runtime.

**Comment by AdrianArroyoCalle** [comment]
Yes, the refresh token is also provided by Google but still not used. I'm aware of this.

**Comment by AdrianArroyoCalle** [comment]
Ok, done in 42b13f0 . You still need to click the button but now most of the time it doesn't ask for a new code
